import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/navBar/mainSideBar";
import { Separator } from "@radix-ui/react-dropdown-menu";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { auth } from "@/lib/auth";
import { SessionProvider } from "next-auth/react";
import { prisma } from "@/lib/prisma";
import { Toaster } from "sonner";
import { PlayerStatsPicker } from "@/components/navBar/PlayerStatsPicker";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  let playerInfo;
  if (session?.user?.id) {
    playerInfo = await prisma.player.findUnique({
      where: {
        userId: session?.user.id,
      },
    });
  } else playerInfo = null;
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={`antialiased`}>
          <SidebarProvider
            style={
              {
                "--sidebar-width": "350px",
              } as React.CSSProperties
            }
          >
            <AppSidebar />
            <SidebarInset>
              <header className="sticky h-14 top-0 flex justify-between shrink-0 items-center gap-2 border-b bg-background p-4 z-50">
                <SidebarTrigger className="-ml-1" />
                <Separator className="mr-2 h-4" />
                {/* if player is logged in show Inventory, else sugguest login */}

                <PlayerStatsPicker player={playerInfo} />
              </header>
              <div className="flex flex-1 flex-col gap-4 ">{children}</div>
            </SidebarInset>
          </SidebarProvider>
          <Analytics />
          <Toaster />
        </body>
      </SessionProvider>
    </html>
  );
}
